import streamlit as st
import pandas as pd
import joblib
import numpy as np
from fpdf import FPDF

st.set_page_config(page_title="CervixNet-Ensemble", page_icon="🩺", layout="wide")

# CSS: High Contrast Medical UI
st.markdown('''
    <style>
    .stApp { background-color: #f8f9fa; }
    [data-testid="stSidebar"] { background-color: #1e272e; }
    h1, h2, h3, h4, h5, p, span, label { color: #2c3e50 !important; }
    .stMetric { background-color: #ffffff; padding: 20px; border-radius: 15px; border-left: 5px solid #3498db; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    .result-card { padding: 25px; border-radius: 15px; margin-bottom: 20px; border: 1px solid #dcdde1; }
    .high-risk { background-color: #ff7675; color: white !important; }
    .low-risk { background-color: #55efc4; color: #2d3436 !important; }
    .result-card h2, .result-card p { color: inherit !important; }
    [data-testid="stSidebar"] label, [data-testid="stSidebar"] p { color: white !important; }
    </style>
''', unsafe_allow_html=True)

@st.cache_resource
def load_assets():
    return joblib.load('CervixNet_Ensemble_Final.pkl'), joblib.load('scaler.pkl'), joblib.load('best_threshold.pkl')

model, scaler, threshold = load_assets()

def generate_pdf(data, risk, status):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 15, txt="CervixNet-Ensemble Diagnostic Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    for k, v in data.items(): pdf.cell(100, 10, txt=f"{k}: {v}", ln=True)
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"Analysis: {status}", ln=True)
    pdf.cell(200, 10, txt=f"Risk Score: {risk:.2f}%", ln=True)
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, txt="Disclaimer: This report is generated by an AI research model and is intended for clinical decision support.")
    return pdf.output(dest='S').encode('latin-1')

# Sidebar for Inputs
with st.sidebar:
    st.header("📋 Patient Data")
    age = st.number_input("Age", 13, 85, 30)
    partners = st.number_input("Sexual Partners", 1, 20, 2)
    first_sex = st.number_input("Age at First Sex", 10, 40, 18)
    pregnancies = st.number_input("Total Pregnancies", 0, 15, 2)
    smokes_yrs = st.number_input("Smoking Years", 0.0, 50.0, 0.0)
    hormonal_yrs = st.number_input("Hormonal Contraceptives (yrs)", 0.0, 30.0, 0.0)
    st.markdown("---")
    vaccine = st.selectbox("HPV Vaccine", ["No", "Yes"])
    bleeding = st.checkbox("Abnormal Bleeding")
    pain = st.checkbox("Pelvic Pain")

# Inference Logic
df = pd.DataFrame([{'Age': age, 'Number of sexual partners': partners, 'First sexual intercourse': first_sex, 
                    'Num of pregnancies': pregnancies, 'Smokes (years)': smokes_yrs, 'Hormonal Contraceptives (years)': hormonal_yrs}])
expected_cols = scaler.feature_names_in_
for col in expected_cols:
    if col not in df.columns: df[col] = 0

input_scaled = scaler.transform(df[expected_cols])
proba_out = model.predict_proba(input_scaled)

# FIXED: Safe probability extraction for multi-dimensional arrays
if isinstance(proba_out, np.ndarray) and proba_out.ndim > 1:
    base_proba = float(proba_out[0][1])
else:
    base_proba = float(np.ravel(proba_out)[-1])

adj_proba = base_proba + (0.12 if (bleeding or pain) else 0)
if vaccine == "Yes": adj_proba -= 0.05
final_proba = float(np.clip(adj_proba, 0, 1))
risk_percent = final_proba * 100

# Fix threshold comparison
t_val = float(np.ravel(threshold)[0])
status = "HIGH RISK" if final_proba >= t_val else "LOW RISK"

# Main Layout
st.title("🩺 CervixNet-Ensemble")
st.subheader("Stacked Meta-Learning MLOps Pipeline | Explainable AI")
st.markdown("---")

col_left, col_right = st.columns(2)

with col_left:
    st.markdown("### 📊 Analysis Output")
    if status == "HIGH RISK":
        st.markdown(f'<div class="result-card high-risk"><h2>⚠️ {status}</h2><p>High oncogenic risk detected. Clinical referral advised.</p></div>', unsafe_allow_html=True)
    else:
        st.markdown(f'<div class="result-card low-risk"><h2>✅ {status}</h2><p>Patient parameters within safe threshold. Routine screening recommended.</p></div>', unsafe_allow_html=True)

with col_right:
    st.markdown("### 📈 Risk Score")
    st.metric("Probability Index", f"{risk_percent:.2f}%")
    st.progress(final_proba)
    
    # PDF Button
    pdf_bytes = generate_pdf({"Age": age, "Pregnancies": pregnancies}, risk_percent, status)
    st.download_button("📥 Export Diagnostic Report (PDF)", pdf_bytes, "CervixNet_Report.pdf", "application/pdf")

st.markdown("---")
st.warning("⚠️ **Disclaimer:** This tool is for research and clinical decision support purposes only. Always seek the advice of a qualified health provider.")
